#ifndef LIBS_LIST_HPP
#define LIBS_LIST_HPP

#include "shared/Type.hpp"

namespace Autolang {
class ACompiler;
namespace Libs {
namespace array {
AObject *add(NativeFuncInData);
AObject *reserve(NativeFuncInData);
AObject *insert(NativeFuncInData);
AObject *pop(NativeFuncInData);
AObject *index_of(NativeFuncInData);
AObject *for_each(NativeFuncInData);
AObject *for_each_with_index(NativeFuncInData);
AObject *for_each_indexed(NativeFuncInData);
AObject *slice(NativeFuncInData);
AObject *reversed(NativeFuncInData);
AObject *filter(NativeFuncInData);
AObject *sort(NativeFuncInData);
AObject *sort_default(NativeFuncInData);
AObject *remove(NativeFuncInData);
AObject *size(NativeFuncInData);
AObject *is_empty(NativeFuncInData);
AObject *get(NativeFuncInData);
AObject *set(NativeFuncInData);
AObject *clear(NativeFuncInData);
AObject *contains(NativeFuncInData);
AObject *to_string(NativeFuncInData);
AObject *join_to_string(NativeFuncInData);
AObject *clone(NativeFuncInData);
AObject *sorted(NativeFuncInData);
AObject *map(NativeFuncInData);
AObject *map_indexed(NativeFuncInData);
AObject *reduce(NativeFuncInData);
AObject *fold(NativeFuncInData);
AObject *first(NativeFuncInData);
AObject *first_or_null(NativeFuncInData);
AObject *last(NativeFuncInData);
AObject *last_or_null(NativeFuncInData);
AObject *take(NativeFuncInData);
AObject *drop(NativeFuncInData);
AObject *any(NativeFuncInData);
AObject *any_fn(NativeFuncInData);
AObject *all_fn(NativeFuncInData);
AObject *none(NativeFuncInData);
AObject *none_fn(NativeFuncInData);
AObject *count_fn(NativeFuncInData);
AObject *sum(NativeFuncInData);
AObject *average(NativeFuncInData);
AObject *max_or_null(NativeFuncInData);
AObject *min_or_null(NativeFuncInData);
AObject *plus(NativeFuncInData);
AObject *minus(NativeFuncInData);
AObject *find(NativeFuncInData);
AObject *find_last(NativeFuncInData);
AObject *filter_not(NativeFuncInData);
AObject *filter_not_null(NativeFuncInData);
AObject *distinct(NativeFuncInData);
AObject *take_last(NativeFuncInData);
AObject *drop_last(NativeFuncInData);
AObject *take_while(NativeFuncInData);
AObject *drop_while(NativeFuncInData);
AObject *chunked(NativeFuncInData);
AObject *to_set(NativeFuncInData);
AObject *sum_of(NativeFuncInData);
AObject *is_not_empty(NativeFuncInData);
AObject *get_or_null(NativeFuncInData);
AObject *get_or_else(NativeFuncInData);
AObject *sorted_descending(NativeFuncInData);
AObject *index_of_first(NativeFuncInData);
AObject *index_of_last(NativeFuncInData);
AObject *single(NativeFuncInData);
AObject *single_or_null(NativeFuncInData);
AObject *sorted_by(NativeFuncInData);
AObject *sorted_by_descending(NativeFuncInData);
AObject *then_by(NativeFuncInData);
AObject *then_by_descending(NativeFuncInData);
AObject *sorted_with(NativeFuncInData);
AObject *sort_with(NativeFuncInData);
AObject *min_by_or_null(NativeFuncInData);
AObject *max_by_or_null(NativeFuncInData);
AObject *distinct_by(NativeFuncInData);
AObject *shuffled(NativeFuncInData);
AObject *flatten(NativeFuncInData);
AObject *group_by(NativeFuncInData);
AObject *associate_by(NativeFuncInData);
AObject *remove_element(NativeFuncInData);
AObject *remove_at(NativeFuncInData);
AObject *add_all(NativeFuncInData);
AObject *remove_all(NativeFuncInData);
AObject *retain_all(NativeFuncInData);
AObject *contains_all(NativeFuncInData);
AObject *flat_map(NativeFuncInData);
AObject *zip(NativeFuncInData);
AObject *unzip(NativeFuncInData);
AObject *windowed(NativeFuncInData);
AObject *partition(NativeFuncInData);
AObject *associate(NativeFuncInData);
AObject *associate_with(NativeFuncInData);
AObject *map_not_null(NativeFuncInData);
AObject *map_indexed_not_null(NativeFuncInData);
AObject *filter_indexed(NativeFuncInData);
AObject *first_fn(NativeFuncInData);
AObject *last_fn(NativeFuncInData);
AObject *single_fn(NativeFuncInData);
AObject *single_or_null_fn(NativeFuncInData);
AObject *last_index_of(NativeFuncInData);
AObject *last_index(NativeFuncInData);
AObject *indices(NativeFuncInData);
AObject *on_each(NativeFuncInData);
AObject *on_each_indexed(NativeFuncInData);
std::string to_string(ANotifier &notifier, AObject *obj);
} // namespace array
} // namespace Libs
} // namespace Autolang

#endif