/*

@brief Parse and load variable in function and class
             Build AST Node
@param in_func -> input (context, compile), in_data -> (context, compile)
@param i -> Current position
@details Handle keywords 'val', 'var', 'static', 'public', 'private',
'protected'
@note Use std::unique_ptr to make it safer
             Use raw pointer release it because it will push to other managers

*/

#ifndef DEBUGGER_DECLARATION_CPP
#define DEBUGGER_DECLARATION_CPP

#include "frontend/parser/Debugger.hpp"
#include "shared/Utils.hpp"

namespace AutoLang {

HasClassIdNode *loadDeclaration(in_func, size_t &i) {
	ensureNoAnnotations(in_data, i);
	auto declaration = &context.tokens[i];
	bool isVal = declaration->type == Lexer::TokenType::VAL;
	bool isGlobal = (!context.currentClassId) &&
	                context.currentFunctionId == context.mainFunctionId;
	bool isInFunction = !context.currentClassId ||
	                    context.currentFunctionId != context.mainFunctionId;
	bool isStatic = context.modifierflags & ModifierFlags::MF_STATIC;
	if (isStatic) {
		isGlobal = true;
		context.modifierflags &= ~ModifierFlags::MF_STATIC;
	}
	bool autogeneratedValue = false;
	bool isLateinit = context.modifierflags & ModifierFlags::MF_LATEINIT;
	if (isLateinit) {
		context.modifierflags &= ~ModifierFlags::MF_LATEINIT;
	}
	Lexer::TokenType accessModifier = getAndEnsureOneAccessModifier(in_data, i);
	context.modifierflags = 0;
	Lexer::Token *token = &context.tokens[i];
	uint32_t firstLine = token->line;
	// Name
	if (!nextTokenSameLine(&token, context.tokens, i, declaration->line) ||
	    !expect(token, Lexer::TokenType::IDENTIFIER)) {
		--i;
		throw ParserError(context.tokens[i].line,
		                  "Expected name but not found");
	}
	{
		std::string message =
		    context.checkValidDeclarationName(token->indexData);
		if (!message.empty()) {
			throw ParserError(token->line, message);
		}
	}
	LexerStringId baseName = token->indexData;
	std::string &name = context.lexerString[token->indexData];
	if (context.currentClassId) {
		auto classInfo = context.getCurrentClassInfo(in_data);
		if (isMapExist(context.getCurrentClass(in_data)->memberMap, name) ||
		    classInfo->staticMember.find(baseName) !=
		        classInfo->staticMember.end())
			throw ParserError(token->line,
			                  "Declaration: Redefination variable name \"" +
			                      name + "\"");
	}
	// Sugar syntax val a? = 1
	bool nullable = true;
	bool sugarSyntax = false;
	if (!nextTokenSameLine(&token, context.tokens, i, declaration->line)) {
		--i;
		throw ParserError(firstLine, "Expected class name but not found");
	}
	if (expect(token, Lexer::TokenType::QMARK)) {
		sugarSyntax = true;
		// Class name
		if (!nextTokenSameLine(&token, context.tokens, i, declaration->line)) {
			--i;
			throw ParserError(firstLine, "Expected class name but not found");
		}
	} else if (expect(token, Lexer::TokenType::EXMARK)) {
		sugarSyntax = true;
		nullable = false;
		// Class name
		if (!nextTokenSameLine(&token, context.tokens, i, declaration->line)) {
			--i;
			throw ParserError(firstLine, "Expected class name but not found");
		}
	}
	HasClassIdNode *value = nullptr;
	ClassDeclaration *classDeclaration = nullptr;
	if (expect(token, Lexer::TokenType::COLON)) {
		classDeclaration =
		    loadClassDeclaration(in_data, i, declaration->line, false);
		context.allClassDeclarations.push_back(classDeclaration);
		if (sugarSyntax) {
			throw ParserError(
			    token->line,
			    std::string("Sugar syntax ") + (isVal ? "val " : "var ") +
			        name + (nullable ? "?" : "!") +
			        " can be used when fast declare, cannot use with " +
			        classDeclaration->getName(in_data) + "? " + "use " +
			        (isVal ? "val " : "var ") + name + ": " +
			        classDeclaration->getName(in_data) +
			        (nullable ? "?" : "!") + " instead of");
		}
		nullable = classDeclaration->nullable;
		if (!nextTokenSameLine(&token, context.tokens, i, declaration->line)) {
			// if (nullable) {
			--i;
			autogeneratedValue = true;
			value = context.constValuePool.push(firstLine,
			                                    DefaultClass::nullObject, 0);
			goto createNode;
			// }
			// --i;
			// throw ParserError(context.tokens[i].line,
			//                   " Expected value but not found");
		}
		// if (!nextTokenSameLine(&token, context.tokens, i, declaration->line)
		// || 	 !expect(token, Lexer::TokenType::IDENTIFIER)) { 	throw
		// std::runtime_error("Expected class name but not found");
		// }
		// className = context.lexerString[token->indexData];
		// if (className == "Null")
		// 	throw std::runtime_error(name + " cannot declarate variable of type
		// Null"); if (!nextTokenSameLine(&token, context.tokens, i,
		// declaration->line)) {
		// 	--i;
		// 	goto createNode;
		// }
	}
	// Value
	if (expect(token, Lexer::TokenType::EQUAL)) {
		if (!nextToken(&token, context.tokens, i)) {
			--i;
			throw ParserError(context.tokens[i].line,
			                  "Expected expression after '=' but not found");
		}
		bool lastJustFindStatic = context.justFindStatic;
		context.justFindStatic = isStatic;
		value = loadExpression(in_data, 0, i);
		if (!classDeclaration && value->kind == NodeType::CONST &&
		    value->classId == DefaultClass::nullClassId) {
			throw ParserError(token->line, "Unknow what type of " + name);
		}
		context.justFindStatic = lastJustFindStatic;
	} else {
		if (!classDeclaration) {
			throw ParserError(token->line, "Unknow what type of " + name);
		}
		autogeneratedValue = true;
		value =
		    context.constValuePool.push(firstLine, DefaultClass::nullObject, 0);
		--i;
	}
createNode:;
	std::string declarationName;
	if (isStatic) {
		if (context.currentFunctionId != context.mainFunctionId)
			declarationName =
			    context.getCurrentFunction(in_data)->name + '.' + name;
		if (context.currentClassId)
			declarationName =
			    context.getCurrentClass(in_data)->name + '.' + name;
	} else
		declarationName = name;

	// if (value->kind == NodeType::CONST && value->isNullable()) {
	// 	if (!nullable) {
	// 		throw ParserError(
	// 		    token->line,
	// 		    declarationName +
	// 		        " is marked non nullable, cannot detach null value");
	// 	}
	// 	if (!classDeclaration) {
	// 		throw ParserError(
	// 		    token->line, std::string("Ambiguous call nullable ") +
	// 		                     (isVal ? "val " : "var ") + name + "? = null");
	// 	}
	// }

	auto node = context.makeDeclarationNode(
	    in_data, token->line, false, baseName, declarationName,
	    classDeclaration, isVal, isGlobal, nullable, isInFunction);
	node->accessModifier = accessModifier;
	node->mustInferenceNullable = !sugarSyntax && !classDeclaration;
	// printDebug(node->name + " is " + (node->accessModifier ==
	// Lexer::TokenType::PUBLIC ? "public" : "private")); printDebug((isVal ?
	// "val " : "var ") + name + " has id " + std::to_string(node->id) + " " +
	// (isGlobal ? "1 " : "0 " ) + (isStatic ? "1 " : "0 "));
	if (isStatic) {
		// Function
		auto funcInfo = context.getCurrentFunctionInfo(in_data);
		if (context.currentFunctionId != context.mainFunctionId) {
			auto it = funcInfo->scopes.back().find(declarationName);
			if (it != funcInfo->scopes.back().end())
				throw ParserError(token->line, declarationName + " has exist");
			funcInfo->scopes.back()[name] = node;
			if (funcInfo->genericData) {
				funcInfo->genericData->staticDeclaration.push_back(
				    {node,
				     (isLateinit && autogeneratedValue) ? nullptr : value});
			}
		} else { // Class
			auto *classInfo = context.getCurrentClassInfo(in_data);
			classInfo->staticMember[baseName] = node;
			if (classInfo->genericData) {
				classInfo->genericData->staticDeclaration.push_back(
				    {node,
				     (isLateinit && autogeneratedValue) ? nullptr : value});
			}
		}
		if (isLateinit && autogeneratedValue) {
			return nullptr;
		}
		auto setNode = context.setValuePool.push(
		    firstLine, context.varPool.push(firstLine, node, false, true),
		    value, true);
		context.staticNode.push_back(setNode);
		return nullptr;
	}
	// Non static
	if (context.currentClassId &&
	    context.currentFunctionId == context.mainFunctionId) {
		auto clazz = context.getCurrentClass(in_data);
		auto classInfo = context.getCurrentClassInfo(in_data);
		uint32_t nodeId = clazz->memberId.size();
		// printDebug(compile.classes[context.currentClassInfo->declarationThis->classId]->name);
		// printDebug((uintptr_t)context.currentClass);
		// std::cout << nodeId << " is node id of " << name <<'\n';
		clazz->memberMap[node->name] = nodeId;
		clazz->memberId.push_back(0);
		// Add member id
		node->id = nodeId;

		// Add Member
		classInfo->member.push_back(node);
		if (isLateinit && autogeneratedValue) {
			return nullptr;
		}
		auto setNode = context.setValuePool.push(
		    firstLine,
		    context.getPropPool.push(
		        firstLine, node, context.currentClassId,
		        context.varPool.push(firstLine, classInfo->declarationThis,
		                             false, false),
		        node->baseName, true, true, false),
		    value, false);
		return setNode;
	}
	if (isLateinit && autogeneratedValue) {
		return nullptr;
	}
	return context.setValuePool.push(
	    firstLine, context.varPool.push(firstLine, node, true, true), value,
	    false);
}

ClassDeclaration *loadClassDeclaration(in_func, size_t &i, uint32_t line,
                                       bool allowReturnVoid) { // Has check
	Lexer::Token *token;
	if (!nextTokenSameLine(&token, context.tokens, i, line) ||
	    !expect(token, Lexer::TokenType::IDENTIFIER)) {
		--i;
		throw ParserError(
		    context.tokens[i].line,
		    "LoadClassDeclaration: Expected class name but not found");
	}
	ClassDeclaration *result = context.classDeclarationAllocator.push();
	// auto currentFuncInfo = context.getCurrentFunctionInfo(in_data);
	auto genericDeclaration =
	    context.preloadGenericData == nullptr
	        ? nullptr
	        : context.preloadGenericData->findDeclaration(token->indexData);
	if (genericDeclaration) {
		result->isGenericDeclaration = true;
		result->classId = DefaultClass::nullClassId;
		genericDeclaration->allClassDeclarations.push_back(result);
	} else if (context.currentClassId) {
		auto currentClassInfo = context.getCurrentClassInfo(in_data);
		auto genericDeclaration =
		    currentClassInfo->findGenericDeclaration(token->indexData);
		if (genericDeclaration) {
			result->isGenericDeclaration = true;
			result->classId = DefaultClass::nullClassId;
			genericDeclaration->allClassDeclarations.push_back(result);
		}
	}
	result->line = token->line;
	result->baseClassLexerStringId = token->indexData;
	switch (token->indexData) {
		case lexerIdNull: {
			throw ParserError(token->line,
			                  "Null cannot used as a type for declaration");
		}
		case lexerIdVoid: {
			if (!allowReturnVoid) {
				throw ParserError(token->line,
				                  "Void cannot used as a type for declaration");
			}
			break;
		}
	}
	if (!nextTokenSameLine(&token, context.tokens, i, line) ||
	    expect(token, Lexer::TokenType::GT)) {
		--i;
		return result;
	}
	if (expect(token, Lexer::TokenType::LT)) {
		loadListGenericDeclarationType(in_data, i, line, allowReturnVoid,
		                               result->inputClassId);
		if (!nextToken(&token, context.tokens, i)) {
			--i;
			return result;
			// throw ParserError(context.tokens[i].line,
			//                   "Generics class must have body");
		}
	}
	if (expect(token, Lexer::TokenType::QMARK)) {
		result->mustInference = false;
		result->nullable = true;
		return result;
	}
	if (expect(token, Lexer::TokenType::EXMARK)) {
		result->mustInference = false;
		result->nullable = false;
		return result;
	}
	--i;
	return result;
}

void loadListGenericDeclarationType(
    in_func, size_t &i, uint32_t line, bool allowReturnVoid,
    std::vector<ClassDeclaration *> &inputVecs) {
	Lexer::Token *token;
	while (true) {
		auto classDeclaration =
		    loadClassDeclaration(in_data, i, line, allowReturnVoid);
		inputVecs.push_back(classDeclaration);
		if (!nextToken(&token, context.tokens, i)) {
			--i;
			throw ParserError(context.tokens[i].line,
			                  "Expected '>' after class name but not found");
		}
		switch (token->type) {
			case Lexer::TokenType::COMMA: {
				break;
			}
			case Lexer::TokenType::GT: {
				return;
			}
			default: {
				throw ParserError(
				    line, "Expected '>' after class name but not found");
			}
		}
	}
}

} // namespace AutoLang

#endif