#ifndef AUTOLANG_HPP
#define AUTOLANG_HPP

#include "backend/vm/AVM.cpp"
#include "backend/vm/AVMLog.cpp"
#include "frontend/parser/Debugger.cpp"
#include "shared/AObject.cpp"
#include "shared/CompiledProgram.cpp"
#include "frontend/parser/DebuggerConditionStatement.cpp"
#include "frontend/parser/DebuggerClass.cpp"
#include "frontend/parser/DebuggerDeclaration.cpp"
#include "frontend/parser/DebuggerFunction.cpp"
#include "frontend/parser/DebuggerLoop.cpp"
#include "shared/DefaultClass.cpp"
#include "shared/DefaultFunction.cpp"
#include "frontend/parser/node/OptimizeNode.cpp"
#include "frontend/lexer/Lexer.cpp"
#include "frontend/parser/node/Node.cpp"
#include "frontend/parser/node/BlockNode.cpp"
#include "frontend/parser/node/CreateNode.cpp"
#include "frontend/parser/node/NodeOptimize.cpp"
#include "frontend/parser/node/NodePutbytecode.cpp"
#include "frontend/parser/node/NullCoalescingNode.cpp"
#include "frontend/parser/node/OptionalAccessNode.cpp"
#include "frontend/parser/node/BinaryNode.cpp"
#include "frontend/parser/ParserContext.cpp"
#include "shared/StackAllocator.cpp"
#include "shared/ObjectManager.cpp"
#include "shared/AreaAllocator.cpp"
#include "frontend/libs/Math.cpp"

#endif